airflow_db:
  outputs:
    dev:
      type: postgres
      threads: '{{env_var("DBT_THREADS")}}'
      host: '{{env_var("DBT_HOST")}}'
      port: '{{env_var("DBT_POST")}}'
      user: '{{env_var("DBT_USER")}}'
      pass: '{{env_var("DBT_PWD")}}'
      dbname: '{{env_var("DBT_DBNAME")}}'
      schema: '{{env_var("DBT_SCHEMA")}}'
  target: dev